### ISSUE TITLE
Distribution build is incompatible with Content-Security-Policy that forbids unsafe-eval

### ISSUE THREAD

**Issue by boutell** [ColdHandz/Vue-Click-Outside-Element#1]
No problem with the code itself, but the package exports a distribution build that relies on "eval," which makes it incompatible with a strict Content-Security-Policy. Please distribute a build that does not rely on "eval."

Thanks for your work on this module, it is appreciated!

**Comment by ColtHands** [comment]
@boutell thank you for your contribution and for using my pkg

Version 14 was built incorrectly and I've deprecated it, you can use versions

1.0.11
1.0.12
1.0.13
~~1.0.14~~
1.0.15

Basically, anything from 11 to 15, but not 14, as they are built almost identical.

**Comment by boutell** [comment]
Confirmed, thanks.
